name: Docker Image CI

on:
  push:
    branches: [ "Powered-by-Valeroso-City-1111-and-The-Valeroso-City-8000" ]
  pull_request:
    branches: [ "Powered-by-Valeroso-City-1111-and-The-Valeroso-City-8000" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
